require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/seasons", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Season. As you add validations to Season, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Season.create! valid_attributes
      get seasons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      season = Season.create! valid_attributes
      get season_url(season)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_season_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      season = Season.create! valid_attributes
      get edit_season_url(season)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Season" do
        expect {
          post seasons_url, params: { season: valid_attributes }
        }.to change(Season, :count).by(1)
      end

      it "redirects to the created season" do
        post seasons_url, params: { season: valid_attributes }
        expect(response).to redirect_to(season_url(Season.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Season" do
        expect {
          post seasons_url, params: { season: invalid_attributes }
        }.to change(Season, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post seasons_url, params: { season: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested season" do
        season = Season.create! valid_attributes
        patch season_url(season), params: { season: new_attributes }
        season.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the season" do
        season = Season.create! valid_attributes
        patch season_url(season), params: { season: new_attributes }
        season.reload
        expect(response).to redirect_to(season_url(season))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        season = Season.create! valid_attributes
        patch season_url(season), params: { season: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested season" do
      season = Season.create! valid_attributes
      expect {
        delete season_url(season)
      }.to change(Season, :count).by(-1)
    end

    it "redirects to the seasons list" do
      season = Season.create! valid_attributes
      delete season_url(season)
      expect(response).to redirect_to(seasons_url)
    end
  end
end
